### ISSUE TITLE
Text on buttons is truncated under Ubuntu Linux

### ISSUE THREAD

**Issue by Xandroff** [KaplanOpenSource/qgis-open-data#2]
![Screenshot at 2019-11-20 10-58-49](https://user-images.githubusercontent.com/12762102/69328519-477ff180-0c47-11ea-992d-71689bc8031e.png)
As per the screenshot.
Observed on Ubuntu (Mate) 18.04.

**Comment by kaplanlior** [comment]
Thanks for reporting. Can you add a few details about the environment -  Uubunu version, is that mate UI ? which QGIS version? and screen resolution. 

I'm asking these are on mate environment on Debian testing with QGIS 3.4.x I don't have this issue (as you can see at here).
![image](https://user-images.githubusercontent.com/2017058/69381476-80f34400-0cbd-11ea-82df-dd8d9fe33548.png)

**Comment by Xandroff** [comment]
> 
> 
> Thanks for reporting. Can you add a few details about the environment - Uubunu version, is that mate UI ? which QGIS version? and screen resolution.
> 
> I'm asking these are on mate environment on Debian testing with QGIS 3.4.x I don't have this issue (as you can see at here).
> ![image](https://user-images.githubusercontent.com/2017058/69381476-80f34400-0cbd-11ea-82df-dd8d9fe33548.png)

I'm using QGIS 3.4.x on Ubuntu Mate 18.04@1920*1080 screen resolution. I've seen this also on vanilla Ubuntu 18.04.
