### ISSUE TITLE
Clicking button 'Browser' before connection throws a python error

### ISSUE THREAD

**Issue by rduivenvoorde** [KaplanOpenSource/qgis-open-data#3]
As I am not able to read the button text :-)

![Screenshot-20200618171109-667x748](https://user-images.githubusercontent.com/731673/85038902-6f0c4d80-b187-11ea-93e2-a2da1927c20d.png)

I clicked the only one I reckocnize: 'Browser' 

Which then throws:

![Screenshot-20200618171336-1232x612](https://user-images.githubusercontent.com/731673/85038745-3ec4af00-b187-11ea-84b3-80496ea85b33.png)

Is it difficult to also create an english version?

**Comment by kaplanlior** [comment]
Thanks for reporting this issue. The browse button isn't relevant without having the list appear first.
But it shouldn't throw an error in any case.
