### ISSUE TITLE
Rename the plugin folder

### ISSUE THREAD

**Issue by Gustry** [KaplanOpenSource/qgis-open-data#5]
The current plugin folder is `opendata_loader`. This is very generic, while your plugin apply only in Israel.

Can you rename the folder? `israel_opendata_loader` ?

AFAIK, the folder can't be renamed after the first publication, because the plugin folder must stay the same for upgrade later.

**Comment by kaplanlior** [comment]
Done, thanks for the comments and approving the plugin.
